name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Make sure you have a requirements.txt file

    - name: List contents of src directory
      run: ls -la src  # This will show you the files in the src directory
    - name: Run main.py
      run: |
         python3 src/cronda.py  # Remove the leading slash
     

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes before deploying

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'  # Set your AWS region
      run: |
        # Commands to deploy your application
        # For example, if you're using AWS CLI to upload to S3:
        aws s3 cp ./cronda s3://crondabuc2/ --recursive  # Adjust as needed

    - name: Notify deployment
      run: |
        echo "Deployment completed successfully!"
