name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: List contents of src directory
      run: ls -la src

    - name: Run cronda.py
      run: |
         python3 src/cronda.py  # No need for AWS env vars; credentials are loaded from secrets.json

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to AWS
      run: |
        aws s3 cp ./cronda s3://crondabuc2/ --recursive

    - name: Notify deployment
      run: echo "Deployment completed successfully!"
